---
defaultStorageEngineId: "${OPENCGA.STORAGE.DEFAULT_ENGINE}"
logLevel: "info"
logFile: ""

## CellBase client configuration, this is used mainly when annotating variants
## This can be set up using maven profiles in your .m2/settings.xml
cellbase:
  hosts:      ## 'remote' URL hosts to annotate variants, for example: http://bioinfo.hpc.cam.ac.uk/cellbase/
  - "${OPENCGA.CELLBASE.REST.HOST}"
  version: "${OPENCGA.CELLBASE.VERSION}"
  database:   ## 'local' connection to CellBase MongoDB
    hosts:
    - "${OPENCGA.CELLBASE.DB.HOST}"
    user: "${OPENCGA.CELLBASE.DB.USER}"
    password: "${OPENCGA.CELLBASE.DB.PASSWORD}"
    options:         ## This is intended for database specific options such as --authenticationDatabase in MongoDB
      authenticationDatabase: "${OPENCGA.CELLBASE.DB.AUTHENTICATION_DATABASE}"
      readPreference: "${OPENCGA.CELLBASE.DB.READ_PREFERENCE}"

  preferred: "remote"   ## This accept two values: 'local' and 'remote' to fetch data

## Storage Query Server configuration. When CLI is launched in 'server' mode a RESTful web server
## is launched in the specified port. Only authorized hosts are allowed to query data.
server:
  rest: 9090
  grpc: 9091
  authManager: "org.opencb.opencga.storage.server.common.DefaultAuthManager"       ## Path to the AuthManager implementation class
  storageEngine: "mongodb"
  authorizedHosts: ["0.0.0.0"]
  options: {}

## Cache Configuration
cache:
  host: ${OPENCGA.STORAGE.CACHE.HOST}
  active: true
  serialization: "json"
  slowThreshold: 50
  allowedTypes: "aln,var"
  maxResultSize: 5000
  password: ""

## Search Configuration
search:
  host: ${OPENCGA.STORAGE.SEARCH.HOST}
  timeout: ${OPENCGA.STORAGE.SEARCH.TIMEOUT}
  collection: "variants"
  user: ""
  password: ""
  rows: 100000

benchmark:
  storageEngine: "mongodb"
  numRepetitions: 20
  load: false
  queries: ["region;gene,ct"]
  databaseName: "opencga"
  table: "variants"
  concurrency: 5
  mode: REST # REST, DIRECT or GRPC
  database:   ## 'local' connection to CellBase MongoDB
      hosts:
      - "localhost:27017"
      user: ""
      password: ""
      options: {}         ## This is intended for database specific options such as --authenticationDatabase in MongoDB

## The following section defines all availables storage engine plugins installed
## Default plugin is 'mongodb' storage engine
storageEngines:
- id: "mongodb"
  options: {}     ## this field is intended to be removed, try not to use it.
  alignment:
#    manager: "org.opencb.opencga.storage.mongodb.alignment.MongoDBAlignmentStorageEngine"
    manager: "org.opencb.opencga.storage.core.alignment.local.DefaultAlignmentStorageEngine"
    options:
      database.name: "opencga"
      tools.samtools: "${OPENCGA.INSTALLATION.DIR}/tools/samtools/samtools"
      transform.region_size: 200000
      transform.coverage_chunk_size: 1000
      mean_coverage_size_list: [200, 10000]
    database:
      hosts:
      - "${OPENCGA.STORAGE.ALIGNMENT.DB.HOSTS}"
      user: "${OPENCGA.STORAGE.ALIGNMENT.DB.USER}"
      password: "${OPENCGA.STORAGE.ALIGNMENT.DB.PASSWORD}"
      options: {}
  variant:
    manager: "org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageEngine"
    options:
      database.name: "opencga"
      dbadaptor.max_timeout : 30000 #(ms) Max allowed timeout for DBAdaptor operations.
      dbadaptor.default_timeout : 10000 #(ms) Default timeout for DBAdaptor operations. Only used if none is provided.
      collection.variants: "variants"
      collection.studies: "studies"
      collection.files: "files"
      include.stats: false
      annotator: cellbase_rest
      annotator.cellbase.exclude: "expression"
      annotator.cellbase.use_cache: true
      species: ${OPENCGA.CLIENT.ORGANISM.SCIENTIFIC_NAME}
      assembly: ${OPENCGA.CLIENT.ORGANISM.ASSEMBLY}
      transform.batch.size: 200
      transform.threads: 4
      transform.format: "avro"
      load.batch.size: 100
      load.threads: 6
      #load.bulk_size: 100
      #load.compress_genotypes: true
    database:
      hosts:
      - "${OPENCGA.STORAGE.VARIANT.DB.HOSTS}"
      user: "${OPENCGA.STORAGE.VARIANT.DB.USER}"
      password: "${OPENCGA.STORAGE.VARIANT.DB.PASSWORD}"
      options:    ## This is intended for database specific options such as --authenticationDatabase in MongoDB
        authenticationDatabase: ${OPENCGA.STORAGE.MONGODB.VARIANT.DB.AUTHENTICATION_DATABASE}
        connectionsPerHost: ${OPENCGA.STORAGE.MONGODB.VARIANT.DB.CONNECTIONS_PER_HOST}
        readPreference: "secondaryPreferred"

## For using this plugin you need to have a Hadoop cluster and run the CLI from a well configured Hadoop client
- id: "hadoop"
  options: {}
  alignment:
    manager: "org.opencb.opencga.storage.hadoop.alignment.MongoDBAlignmentStorageEngine"
    options: {}
    database:
      hosts:
      - "${OPENCGA.STORAGE.ALIGNMENT.DB.HOSTS}"
      user: "${OPENCGA.STORAGE.ALIGNMENT.DB.USER}"
      password: "${OPENCGA.STORAGE.ALIGNMENT.DB.PASSWORD}"
  variant:
    manager: "org.opencb.opencga.storage.hadoop.variant.HadoopVariantStorageEngine"
    options:
      #Generic options
      database.name: "opencga"
      annotator: cellbase_rest
      annotator.cellbase.exclude: "expression"
      annotator.cellbase.use_cache: true
      species: ${OPENCGA.CLIENT.ORGANISM.SCIENTIFIC_NAME}
      assembly: ${OPENCGA.CLIENT.ORGANISM.ASSEMBLY}
      #Plugin specific options
      hadoop.bin: "hadoop"
#      hadoop.env: # See opencga-env.sh
#      - "HADOOP_USER_CLASSPATH_FIRST=true"
#      - "HADOOP_CLASSPATH=$HADOOP_CLASSPATH:${OPENCGA.INSTALLATION.DIR}/libs/protobuf-java-${google.protobuf}.jar"
#      - ....
      opencga.storage.hadoop.jar-with-dependencies: "opencga-storage-hadoop-core-${opencga.version}-jar-with-dependencies.jar"
      opencga.archive.chunk_size: 1000
      hadoop.load.archive.batch.size: 3
      hadoop.load.variant.batch.size: 500
      opencga.archive.table.presplit.size: 500
      opencga.variant.table.presplit.size: 500
      opencga.archive.table.compression: "snappy"
      opencga.variant.table.compression: "snappy"
      opencga.storage.hadoop.variant.hbase.namespace: "${OPENCGA.STORAGE.HADOOP.VARIANT.HBASE.NAMESPACE}"
      opencga.storage.hadoop.variant.archive.table.prefix: "${OPENCGA.STORAGE.HADOOP.VARIANT.ARCHIVE.TABLE.PREFIX}"

### hadoop properties
      mapreduce.map.cpu.vcores: 1
      mapreduce.map.memory.mb: 2560
      opencga.variant.table.mapreduce.map.java.opts: -Xmx2048m,-XX:+UseG1GC,-Djava.util.concurrent.ForkJoinPool.common.parallelism=1
      opencga.storage.hadoop.hbase.merge.archive.scan.batchsize: 2000
      # Increase the ScannerTimeoutPeriod from 60000 (1min) to 300000 (5min) to avoid ScannerTimeoutExceptions
      # See opencb/opencga#352 for more info.
      opencga.storage.hadoop.mapreduce.scanner.timeout: 300000
       # 900000 -> 15 minutes
#      hbase.client.scanner.timeout.period: 900000
#      hbase.rpc.timeout: 900000
###
      #Hadoop options
      #fs.defaultFS: "${OPENCGA.STORAGE.HADOOP.HDFS.DEFAULT_FS}"
    database:
      hosts:
      - "${OPENCGA.STORAGE.HADOOP.VARIANT.DB.HOSTS}"
      user: "${OPENCGA.STORAGE.HADOOP.VARIANT.DB.USER}"
      password: "${OPENCGA.STORAGE.HADOOP.VARIANT.DB.PASSWORD}"
